# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  # config.vm.provision "docker"
  # config.vm.provision :docker_compose
  # config.vm.provision "shell", inline: <<-SHELL
  #    apt-get update
  #    apt-get install -y ruby-dev lv zsh vim build-essential bison
  # SHELL
  config.vm.provision "shell", inline: <<-SHELL
    su - vagrant -c 'command curl -sSL https://rvm.io/mpapis.asc | gpg --import -'
    su - vagrant -c 'command curl -sSL https://get.rvm.io | bash -s stable'
    su - vagrant -c 'rvm install 2.5.0'
  SHELL
  script = <<-SHELL
sudo apt-get install -y python python-pip python-virtualenv
wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
su - vagrant -c 'cd ~ && git clone https://github.com/jiikko/helog && bundle install'
  SHELL
  config.vm.provision "shell", inline: script
end
